name: CI Workflow

on:
  push:
    branches: [main]
    
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]

jobs:
  build:
    runs-on: windows-latest

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v2

      # Install NuGet
      - name: Install NuGet
        run: |
          choco install nuget.commandline

      # Install PowerQuery SDK
      - name: Install PowerQuery SDK
        run: |
          # Install PowerQuery SDK (NuGet install)
          nuget install Microsoft.PowerQuery.SdkTools -Version 2.144.1 -OutputDirectory $env:TEMP\powerquery_sdk

      # Set environment variables and debug the PowerQuerySDKPath
      - name: Set environment variables and debug PowerQuerySDKPath
        run: |
          # Ensure correct path to PowerQuery SDK tools
          $env:PowerQuerySDKPath = "$env:GITHUB_WORKSPACE\_temp\powerquery_sdk\Microsoft.PowerQuery.SdkTools.2.144.1\tools"
          
          # Debug the PowerQuery SDK Path
          Write
