name: CI Workflow

on:
  push:
    branches: [
      main
    ]
    
  pull_request:
    types: [
      opened,
      synchronize,
      reopened,
      ready_for_review
    ]

jobs:
  build:
    runs-on: windows-latest

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v2

      # Install NuGet
      - name: Install NuGet
        run: |
          choco install nuget.commandline

      # Install PowerQuery SDK
      - name: Install PowerQuery SDK
        run: |
          # Install PowerQuery SDK (NuGet install)
          nuget install Microsoft.PowerQuery.SdkTools -Version 2.144.1 -OutputDirectory $env:TEMP\powerquery_sdk

      # Set environment variables
      - name: Set environment variables
        run: |
          $env:PowerQuerySDKPath = "$env:GITHUB_WORKSPACE\_temp\powerquery_sdk\Microsoft.PowerQuery.SdkTools.2.144.1\tools"
          Write-Host "PowerQuery SDK Path: $env:PowerQuerySDKPath"

      # Navigate to Exasol folder and create .mez file using MakePqx
      - name: Create .mez file using MakePqx
        run: |
          # Navigate to the Exasol directory
          cd "$env:GITHUB_WORKSPACE\tests\powerbi-exasol\Exasol\bin\AnyCPU\Debug"

          # Run MakePqx to create the .mez file
          & "$env:PowerQuerySDKPath\MakePqx.exe" -ProjectFile "Exasol.pqproj"

      # Modify RunPQSDKTestSuitesSettings.json file
      - name: Modify RunPQSDKTestSuitesSettings.json file
        run: |
          $filePath = "$env:GITHUB_WORKSPACE\tests\RunPQSDKTestSuitesSettings.json"
          $jsonContent = Get-Content $filePath | ConvertFrom-Json

          # Modify the JSON content
          $jsonContent.PQTestExePath = "$env:PowerQuerySDKPath\PQTest.exe"
          
          # Correct the path to the .mez file (one level back from /tests/)
          $jsonContent.ExtensionPath = "$env:GITHUB_WORKSPACE\powerbi-exasol\Exasol\bin\AnyCPU\Debug\Exasol.mez"

          # Write the modified content back to the file
          $jsonContent | ConvertTo-Json -Compress | Set-Content $filePath

      # Replace placeholders in credentials.json with GitHub secrets
      - name: Replace placeholders in credentials.json
        run: |
          $filePath = "$env:GITHUB_WORKSPACE\tests\credentials.json"
          $jsonContent = Get-Content $filePath | ConvertFrom-Json

          # Replace placeholders with GitHub secrets
          $jsonContent.AuthenticationProperties.Username = "${{ secrets.pbi_username }}"
          $jsonContent.AuthenticationProperties.Password = "${{ secrets.pbi_password }}"

          # Write the modified content back to the file
          $jsonContent | ConvertTo-Json -Compress | Set-Content $filePath

      # Run the PowerShell script with the -DetailedResults flag
      - name: Run PowerShell Test Suite
        run: |
          # Navigate to the tests folder
          cd "$env:GITHUB_WORKSPACE\tests"

          # Run the PowerShell script with the -DetailedResults flag
          .\RunPQSDKTestSuites.ps1 -DetailedResults
